var MAINUI_MIDBTN_START_TYPE = "MAINUI_MIDBTN_START_TYPE";
var MAINUI_MIDBTN_END_TYPE = "MAINUI_MIDBTN_END_TYPE";
var MAINUI_MIDBTN_UPDATE_TYPE = "MAINUI_MIDBTN_UPDATE_TYPE";
//# sourceMappingURL=Const.js.map